packages:
  - apps/*
  - packages/**/*

catalog:
  '@rn-primitives/accordion': 1.1.0
  '@rn-primitives/alert-dialog': 1.1.0
  '@rn-primitives/aspect-ratio': 1.1.0
  '@rn-primitives/avatar': 1.1.0
  '@rn-primitives/checkbox': 1.1.0
  '@rn-primitives/collapsible': 1.1.0
  '@rn-primitives/context-menu': 1.1.0
  '@rn-primitives/dialog': 1.1.0
  '@rn-primitives/dropdown-menu': 1.1.0
  '@rn-primitives/hover-card': 1.1.0
  '@rn-primitives/label': 1.1.0
  '@rn-primitives/menubar': 1.1.0
  '@rn-primitives/navigation-menu': 1.1.0
  '@rn-primitives/popover': 1.1.0
  '@rn-primitives/progress': 1.1.0
  '@rn-primitives/radio-group': 1.1.0
  '@rn-primitives/select': 1.1.0
  '@rn-primitives/separator': 1.1.0
  '@rn-primitives/slot': 1.1.0
  '@rn-primitives/switch': 1.1.0
  '@rn-primitives/table': 1.1.0
  '@rn-primitives/tabs': 1.1.0
  '@rn-primitives/toggle': 1.1.0
  '@rn-primitives/toggle-group': 1.1.0
  '@rn-primitives/tooltip': 1.1.0
  '@rn-primitives/types': 1.1.0
  '@tanstack/react-table': 8.11.7
  autoprefixer: 10.4.20
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.6.2
  class-variance-authority: 0.7.0
  clsx: 2.1.1
  lucide-react: 0.483.0
  lucide-react-native: 0.454.0
  nativewind: 4.1.23
  postcss: 8.4.47
  react-native: 0.76.1
  react-native-reanimated: 3.16.1
  react-native-web: 0.19.13
  tailwind-merge: 2.5.4
  tailwindcss: 3.4.14
  tailwindcss-animate: 1.0.7
  tailwindcss-animate-utils: 1.0.7
