packages:
  - apps/*
  - packages/**/*

catalog:
  autoprefixer: 10.4.20
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.6.2
  class-variance-authority: 0.7.0
  clsx: 2.1.1
  lucide-react: 0.483.0
  lucide-react-native: 0.454.0
  nativewind: 4.1.23
  postcss: 8.4.47
  react-native: 0.76.1
  react-native-reanimated: 3.16.1
  react-native-web: 0.19.13
  tailwind-merge: 2.5.4
  tailwindcss: 3.4.14
  tailwindcss-animate: 1.0.7
